### ISSUE TITLE
Dans la prévisualisation, les éléments normalement en italique s'affichent en gras

### ISSUE THREAD

**Issue by Maiana8L** [daktary-team/scribouilli#121]

**Comment by Maiana8L** [comment]
![image](https://github.com/Scribouilli/scribouilli/assets/124084791/b505b0b1-f183-4cb6-a5d8-f6545d22d246)
ici les noms des autrices sont en italique (et ça apparait bien en italique côté mimoza)

**Comment by DavidBruant** [comment]
Ce problème m'a aussi été remonté par une amie
