### ISSUE TITLE
Les feuilles de style CSS renvoient une erreur 404 après avoir désactivé le Pages Unique Domain

### ISSUE THREAD

**Issue by marienfressinaud** [daktary-team/scribouilli#167]
En suivant les instructions de #150, le site devient effectivement accessible à l’adresse type `<nickname>.monpetitsite.org/<site>`, mais les feuilles de style du thème deviennent inaccessibles.

Par exemple : https://berumuron.monpetitsite.org/lecteurs-de-flux/

J’ai bien regénéré le site après avoir désactivé l’option.
Et ça marchait 100% sûr avant ça.

**Comment by DavidBruant** [comment]
Pour le moment, je recommande de réactiver le Pages Unique Domain (et je vais raconter dans l'autre issue pourquoi on en est là)

Et désolé de ce nom de domaine moisi

**Comment by DavidBruant** [comment]
Ah pardon, ou alors, tu peux aller dans ton fichier `_config.yml` et modifier le `baseurl` pour qu'il vaille `/lecteurs-de-flux`

**Comment by DavidBruant** [comment]
(je me demande si on le réécrit, mais je crois que non, il faudrait que je vérifie)

**Comment by DavidBruant** [comment]
Y'a l'explication longue par ici : https://github.com/Scribouilli/scribouilli/issues/150#issuecomment-1867781564

Et désolé qu'on ne puisse pas proposer beaucoup mieux pour le moment et que tu rencontres ce problème :-/

**Comment by marienfressinaud** [comment]
> Ah pardon, ou alors, tu peux aller dans ton fichier _config.yml et modifier le baseurl pour qu'il vaille /lecteurs-de-flux

C’est parfait ça a marché ! Par contre ça semble réécrire à chaque modif depuis l'atelier donc je vais m'assurer que le site est ok, modifier le `baseurl` et plus y retoucher :D

> Et désolé qu'on ne puisse pas proposer beaucoup mieux pour le moment et que tu rencontres ce problème :-/

Y'a vraiment aucun souci, je suis autonome sur ce problème donc t'en fais pas :) Merci d’avoir pris le temps d’expliquer tout le contexte en détail, ça me permet de bien comprendre ce qu’il se passe :pray:

**Comment by DavidBruant** [comment]
> C’est parfait ça a marché ! 

Ah trop bien !

> Par contre ça semble réécrire à chaque modif depuis l'atelier donc je vais m'assurer que le site est ok, modifier le baseurl et plus y retoucher :D

arf :-p 
Ça me revient. On a pris cette décision pour pouvoir gérer quand une personne installe un nom de domaine custom, pour qu'on soit toujours sychro (on choisit que Scribouilli gère complètement le fichier `_config.yml` pour simplifier la vie des personnes qui n'y connaissent rien). Mais bon, pour ta situation, c'est pas ouf

Ça (et d'autres retours) me donne envie de créer un mode "je sais ce que je fais" dans Scribouilli. Ça serait genre une option dans le `_config.yml` (donc qui n'est modifiée que quand on est assez à l'aise pour trifouiller un fichier qui s'appelle `_config.yml` dans l'interface github ou gitlab) et quand on l'active, par exemple, ça désactive la synchro automatique du `baseurl`, et j'imagine qu'on pourrait relâcher + de contrôle

Je ferme cette issue, parce que le problème est résolu
