### ISSUE TITLE
Scribouilli ne déploie plus sur Github ?

### ISSUE THREAD

**Issue by maiwann** [daktary-team/scribouilli#168]
Je suis allée voir la page https://github.com/topics/site-scribouilli?o=desc&s=updated
Et je constate que les derniers sites n'ont pas d'url à droite, et quand j'ai tapé l'adresse de leur Scribouilli, je suis arrivée sur une 404

Du coup j'ai créé https://github.com/maiwann/testons-donc et le build ne fonctionne pas :/

**Comment by DavidBruant** [comment]
Je vois

```

Run bundle exec jekyll build
bundler: failed to load command: jekyll (/home/runner/work/testons-donc/testons-donc/vendor/bundle/ruby/3.2.0/bin/jekyll)
/opt/hostedtoolcache/Ruby/3.2.2/x64/lib/ruby/gems/3.2.0/gems/bundler-2.4.10/lib/bundler/source/git/git_proxy.rb:329:in `allowed_with_path': The git source https://github.com/Scribouilli/mimoza.git is not yet checked out. Please run `bundle install` before trying to start your application (Bundler::GitError)
```

dans https://github.com/maiwann/testons-donc/actions/runs/7340160124/job/19985705365

Et c'est très zarb 

Je ne vais pas regarder + que ça pour le moment
J'essaye de regarder ça dans les jours qui viennent

**Comment by DavidBruant** [comment]
J'ai supprimé les Gemfiles.lock des site-template
Ça devrait être à nouveau possible de créer et déployer des sites (je n'ai pas testé, mais je vois que les site-template se déploient)

**Comment by DavidBruant** [comment]
Rhhaaaaa
Ça se déploie sans le thème !

**Comment by DavidBruant** [comment]
Je crois que j'ai réussi à résoudre le problème
Je testerai demain, sauf si quelqu'un teste avant moi

**Comment by maiwann** [comment]
YES ! => https://github.com/maiwann/test-du-debug

(il n'y a toujours pas l'url à droite mais osef pour l'instant)

Merci David !

**Comment by Cesese** [comment]
Bonjour, j'ai un problème différent mais je pense que c'est lié. Je viens de créer un site Scribouilli (avec le preset framalibre), mais quand je clique sur "Lancer La Publication", ça ne fait rien et en haut à gauche c'est toujours marqué "✅ Site à jour".
Quand je regarde sur Github, il n'y a pas de nouveau commit. (https://github.com/Cesese/je-danse-le-floss/commits/main/)

Je suis sur firefox, j'utilise des extensions pour la vie privée (Ublock Origin, Privacy Badger, NoScript). J'ai essayé à la fois sur PC et sur téléphone, et j'ai essayé en désactivant les extensions.

J'ai l'impression que le problème vient du site, mais si vous pensez que ça vient de mon setup je peux essayer sur un profile vierge / un autre navigateur.

**Comment by DavidBruant** [comment]
Bonjour @Cesese , merci pour ton commentaire
Je n'arrive pas à reproduire le problème que tu décris
Mon repo : https://github.com/DavidBruant/owner-avatar-je-danse-le-floss-
Le site publié : https://davidbruant.github.io/owner-avatar-je-danse-le-floss-/

Un truc qui me surprend, c'est que je ne vois qu'un seul commit ici : https://github.com/Cesese/je-danse-le-floss/commits/main/
Alors que normalement, il devrait y en avoir 2, comme ici : https://github.com/DavidBruant/owner-avatar-je-danse-le-floss-/commits/main/
(c'est sensé être complètement automatique)

Est-ce que tu peux essayer avec le preset "faire mon site" (ou je ne sais plus quel comment il s'appelle, mais celui qui n'est pas framalibre) ?

**Comment by DavidBruant** [comment]
Je serais surpris que ce comportement vienne des extensions pour la vie privée, mais pour le moment, je ne peux pas l'exclure

**Comment by maiwann** [comment]
Ce problème n'est pas généralisé à tous les sites scribouilli donc on close cette issue, si il y a un souci de ce genre on peut refaire une issue plus précise
