### ISSUE TITLE
🐜 Je peux créer des articles 👍👍👍

### ISSUE THREAD

**Issue by Maiana8L** [daktary-team/scribouilli#17]
## Atelier
- [x] Dans l'atelier j'ai une page "Articles" qui fonctionne comme "Pages"

## Mimoza
- [x] Une entrée "Blog" dans le menu
- [x] Quand je clique sur blog dans mon site j'accède à la liste de mes articles
- [x] Styler un article (comme une page)
- [x] Styler la liste d'articles de Blog - genre blog de [Maïtané](https://maiwann.net/blog/)

**Comment by Maiana8L** [comment]
Je pense ce qui serait ouf c'est qu'on puisse choisir le nom du Menu qui apparait aussi, ça permettrait de l'appeler "Blog" ou "Mes Projets", ou "Mes réalisations"

**Comment by elegaanz** [comment]
Niveau interface :
- [x] on a une partie "Sections supplémentaires" dans les paramètres, avec une checkbox "Ajouter une page articles" et une checkbox "Ajouter une page projets"
- [x] quand les checkbox sont cochées, créer dans le dépôt respectivement un `blog.md` et `projects.md` (cf https://github.com/Scribouilli/mimoza/tree/blog)
- [x] quand elles sont décochées, supprimer ces fichiers, mais pas les dossiers et posts correspondants (mimoza est configuré pour que ça cache la catégorie dans le site)
- [x] le menu article (resp. projets) n'est affiché dans le header de l'atelier que si la fonctionnalité est activé OU si on a déjà des items dans la catégorie

**Comment by Ynote** [comment]
J'ai ajouté une carte dans la [Grainerie] pour un bug : 
- [ ]  la page Articles qui apparaît dans la liste des pages qu'on peut éditer alors que ça ne devrait pas
