### ISSUE TITLE
Quand je suis le parcours pour utiliser Scribouilli avec Gitlab ou Scribougit, j'arrive sur une page vide

### ISSUE THREAD

**Issue by maiwann** [daktary-team/scribouilli#182]
Je vais sur atelier.scribouilli.org , je suis le chemin jusqu'à choisir Scribougit, je dis que j'ai un compte, je clique sur le bouton pour me connecter, et là j'arrive sur une page "vide" :

![image](https://github.com/Scribouilli/scribouilli/assets/27999224/5002be57-a633-4dbc-b95f-3e63bf8c5dfb)

![image](https://github.com/Scribouilli/scribouilli/assets/27999224/5efa6c2a-ace1-4648-9da1-281d80307502)

Je n'ai pas le pb avec Github.
Maiana a le même problème que moi sur son ordi.

Quand je clique depuis cette page blanche sur le logo qui me renvoie vers atelier.scribouilli.org, je me retrouve sur une page avec le loader coeur qui me dit qu'il est en train de chercher si j'ai plusieurs sites.

**Comment by DavidBruant** [comment]
Normalement, c'est corrigé par #183 

Et déso, c'est une erreur de ma part, je n'ai pas assez testé après #180
