### ISSUE TITLE
Je n'arrive pas à ouvrir le site la-palette

### ISSUE THREAD

**Issue by maiwann** [daktary-team/scribouilli#194]
Ca se passe via Github,
c'est un site que j'ai fork pour essayer de le dépanner.

Quand j'essaie dans le sélectionner dans l'atelier, le spinner apparait puis rien ne se passe.

Et dans la console, ça boucle :

![image](https://github.com/Scribouilli/scribouilli/assets/27999224/a42a5574-f48c-423b-8aa7-26eebd98c682)

**Comment by DavidBruant** [comment]
je passe une tête rapidement

J'ai fork et j'ai le même résultat

Le site ne se déploie pas automatiquement sur ton fork ou le mien parce qu'on n'a pas github pages activé

**Comment by DavidBruant** [comment]
Et même quand j'active github pages, je vois une autre erreur : 

> error TypeError: Error in input stream

Quand je clique sur le lien vers le code, ça donne la méthode `static streamReader(stream)` de la `class GitPktLine`
J'imagine que tout ça fait partie d'isomorphic-git

**Comment by DavidBruant** [comment]
En ré-essayant, j'ai un peu + d'erreurs : 
> merge error NotFoundError: Could not find refs/heads/master.

c'est zarb parce qu'on s'en fout un peu normallement de la branche `master`

> Error: ENOENT: /github.com/DavidBruant/la-palette/_config.yml

et c'est zarb parce que y'a bien le fichier `_config.yml` dans le repo (mais bon, j'imagine que cette erreur est une conséquence des précédentes et si on corrige les précédentes, celle-ci n'aura plus lieu)

**Comment by maiwann** [comment]
Je me suis repenché dessus et j'arrive à l'ouvrir ! 
![image](https://github.com/Scribouilli/scribouilli/assets/27999224/4280b554-6bb9-4e3e-8e34-4ef04593e3e7)

J'ai supprimé toutes les images et une page "le festival"

**Comment by maiwann** [comment]
Bon j'ai remis la page "le festival" et toutes les images (en allégeant le poids de certains qui font 14 Mo) et… ça fonctionne toujours alors que j'ai l'impression d'être revenue à la situation initiale 🤔

**Comment by maiwann** [comment]
Bon ben j'ai supprimé le dépot, re-forké, et là je viens de supprimer toutes les images, plusieurs pages… et l'atelier a le bug =/ je ne sais point identifier d'où vient le souci !

**Comment by maiwann** [comment]
OK j'ai recommencé de 0 : 
- J'ai créé un site scribouilli classique
- J'ai copié chacune des pages md et ai mis le même ordre de pages, tout fonctionne bien
- Puis j'ai uploadé toutes les images d'un coup, et là, ça ne fonctionne plus… cf https://github.com/maiwann/palette2/commit/849906989594a89b72b9685a6ce7830fc2ed043e

J'avais fait une manip sur mon ordi pour abaisser le poids des images lors de mes tests précédents, cela pourrait-il être la solution ?!

**Comment by DavidBruant** [comment]
> error TypeError: Error in input stream

Avec cette erreur, ma meilleure hypothèse, c'est un bug côté isomorphic-git
En gros, ptèt un bug dans la ré-implémentation du protocole git, genre une séquence binaire mal interprétée. Et cette séquence a lieu dans un des fichiers image du repo (mais impossible dans des fichiers textes et donc pas trouvée par le projet isomorphic-git jusque-là)

Ça serait cohérent avec le fait qu'on n'arrive pas à reproduire le bug quand on recréé le site avec des images modifiées

**Comment by maiwann** [comment]
Peut-être dans la même veine : 
J'ai essayé d'aider sur ce site Scribouilli hier, en vocal : https://github.com/gaellecouraud/gaellecouraud

La personne a ajouté une image, puis a voulu enregistrer la page. A partir de là, Scribouilli donne l'impression que tout va bien, mais on ne voit aucun nouveau commit sur Github et toute nouvelle modification a l'air de fonctionner dans l'atelier (si j'ajoute une ligne de texte, que je publie, que je rouvre la page dans l'atelier, la ligne est là) mais n'est pas envoyé sur github.

(Grace à une PR depuis github, Scribouilli a identifié qu'il y avait un souci et proposé de résoudre les conflits, ce qui a permis de revenir à une situation normale, donc on a pu rééssayer)

On a changé le nom de l'image, qui comprenait un point, mais le souci a eu lieu à nouveau (cf l'image en question https://grenier.lechappeebelle.team/s/4kNYsNAtpkGoP3b )

Et pour dépanner, j'ai voulu aujourd'hui forker son dépot pour faire les tests et modifs moi-même, mais je n'arrive pas à l'ouvrir avec l'atelier de Scribouilli (je le sélectionne dans la liste déroulante, clique sur "Choisir ce site" et rien ne se passe, dans la console : 

![image](https://github.com/Scribouilli/scribouilli/assets/27999224/f819ce65-86ff-47f5-a69f-d9f7285c1bfa)

Je ne comprends pas si ces 2 problèmes sont liés
