### ISSUE TITLE
Supporter Gitlab pour la publication

### ISSUE THREAD

**Issue by mat-m** [daktary-team/scribouilli#21]
Bonjour

GitLab est une plate-forms similaire à GitHub, mais libre. Elle dispose aussi d'un système d'intégration continue permettant de déployer des pages statiques.
Le gros avantage: GitLab est open-source, et dispose d'une version hébergeable (https://framagit.org, par ex.)

**Comment by DavidBruant** [comment]
ah oui ! Nous connaissons bien Gitlab !\

Le support Gitlab est prévu pour un jour. Et pour le moment, nous priorisons de finir un produit utile basé sur Github. Le support gitlab viendra plus tard

Si tu souhaites qu'il arrive plus tôt, nous pouvons travailler ensemble à le faire advenir. Aurais-tu une disponibilité pour y travailler ?

**Comment by DavidBruant** [comment]
Je ferme cette issue en faveur de https://github.com/Scribouilli/scribouilli/issues/76

Nous sommes activement en train de travailler au support gitlab

Il arrivera dans les semaines qui arrivent
