### ISSUE TITLE
:ant: Je peux utiliser Scribouilli sur plusieurs repo 👍👍

### ISSUE THREAD

**Issue by Ynote** [daktary-team/scribouilli#29]
Scénarii pour la création : 
- L'utilisateurice n'a pas encore d'organisation et de repo : 
  - on lui crée un repo automatiquement
- L'utilisateurice a des organisations : 
  - iel choisit si elle va travailler sur une organisation ou sur son compte personnel.
    - si pas de repo : on met un bouton `créer le site de l'organisation`
    - si des repos : on met la liste des repos disponibles et un formulaire pour créer un nouveau repo.

Il faut également penser à une page pour permettre à l'utilisateurice de changer de repo.

**Comment by maiwann** [comment]
- [x] Oubli : Le bouton dans la page paramètres n'a pas de href=""

**Comment by maiwann** [comment]
- [x] Bug : Comportement inattendu lorsque je veux créer un nouveau site + le bouton disparait (mais ptet c'est voulu ?)

Résolu si on ne met pas d'espaces dans l'input ! 
![image](https://github.com/Scribouilli/scribouilli/assets/27999224/b0e8f7d9-c6d8-484d-bb57-12dd78297b39)

Note : en fait les 2 dépots ont été créés, mais celui avec des espaces a déclenché une erreur 🤔 

![image](https://github.com/Scribouilli/scribouilli/assets/27999224/1230a92c-590f-4fd0-bdf6-0bb6c15f2734)

Du coup est-ce que ça affiche une fausse erreur ?
Est-ce qu'on veut décourager les gens de mettre des espaces ?
Est-ce qu'il faut qu'on gère les espaces d'une façon différente ?

Note bis : J'ai reçu un mail de Github qui a l'air de dire que qqchose va pas alors que ma modif (de style) a fonctionné ?
![image](https://github.com/Scribouilli/scribouilli/assets/27999224/cd5e0056-3823-451f-8cd7-0355ead5a1bc)

**Comment by maiwann** [comment]
[en cours d'investigation]

Mail reçu à l'instant :

> Bonjour Maïtané,
J'ai tout recommencé en prenant en compte tes indications ici : https://chloethorey.github.io/test-website-repo-3796/ pour que les pages soient dans le bon ordre.
Mais aujourd'hui, comme j'avais du temps pour compléter la dernière page et tenter une mise en ligne, je me suis reconnectée via un marque page que je m'étais mis sur scribouilli et je ne retombe pas sur mon projet, mais sur le site  : https://scribouilli.github.io/scribouilli/atelier-list-pages?repoName=test-website-repo-3796&account=[object%20Object]
Est ce qu'il existe une possibilité pour que je retrouve mon projet en cours?

**Comment by elegaanz** [comment]
Ce lien a l'air de marcher (en remplaçant le `[object Object]` dans l'URL par son nom de compte) : https://scribouilli.github.io/scribouilli/atelier-list-pages?repoName=test-website-repo-3796&account=chloethorey

(d'ailleurs il marche pour tout le monde, je sais pas si c'est un problème ou pas, en pratique je ne pense pas qu'on puisse éditer son site, mais ça donne cette impression, et je ne sais pas si c'est un souci ou pas)

**Comment by Ynote** [comment]
> Mais aujourd'hui, comme j'avais du temps pour compléter la dernière page et tenter une mise en ligne, je me suis reconnectée via un marque page que je m'étais mis sur scribouilli et je ne retombe pas sur mon projet, mais sur le site : [https://scribouilli.github.io/scribouilli/atelier-list-pages?repoName=test-website-repo-3796&account=[object%20Object]](https://scribouilli.github.io/scribouilli/atelier-list-pages?repoName=test-website-repo-3796&account=%5Bobject%20Object%5D)

Je ne suis pas certaine de voir exactement à quel moment la redirection fait ça. Je creuse un peu.

> d'ailleurs il marche pour tout le monde, je sais pas si c'est un problème ou pas, en pratique je ne pense pas qu'on puisse éditer son site, mais ça donne cette impression, et je ne sais pas si c'est un souci ou pas

Oui c'est embêtant ça qu'on puisse toustes y accéder, je vais jeter un oeil.

**Comment by Ynote** [comment]
> Du coup est-ce que ça affiche une fausse erreur ?
> Est-ce qu'on veut décourager les gens de mettre des espaces ?
> Est-ce qu'il faut qu'on gère les espaces d'une façon différente ?

@maiwann Je propose pour nous faciliter la vie de décourager les espaces. Plusieurs possiblités (qu'on peut combiner ou pas): 
- on peut ajouter une phrase du type `Choisissez un nom de site avec des caractères alpha-numériques et sans espaces, comme par exemple "mon-fantastique-site-scribouilli"
- on peut ajouter un validateur qui renvoie une erreur si y'a un espace
- on peut ajouter des tirets côté back lorsqu'on envoie le call à l'API GitHub. Quand l'utilisateurice tape `faiseuses du web` on envoie `faiseuses-du-web`.

Ma préférence c'est la 3ème, je crois que les utilisateurices ne vont pas souvent éditer leur repo et vont à peine se rendre compte que les espaces ont été changé en tiret. Mais ça m'embête de faire des trucs sans l'accord des utilisateurices. On peut en discuter de vive voix pour voir ce qu'on choisit de faire.

**Comment by Ynote** [comment]
Je viens de tester et je vois que GitHub transforme les espaces en tiret en fait. On pourrait donc faire pareil.

**Comment by Ynote** [comment]
> d'ailleurs il marche pour tout le monde, je sais pas si c'est un problème ou pas, en pratique je ne pense pas qu'on puisse éditer son site, mais ça donne cette impression, et je ne sais pas si c'est un souci ou pas

J'ai pris le parti pour l'instant de rediriger si on n'est pas owner du repo (cf. https://github.com/Scribouilli/scribouilli/pull/39). Je me permets de merger cette PR car je pense que ce sera nécessaire dans tous les cas de faire ce check lorsqu'on ajoutera les organisations.

**Comment by Ynote** [comment]
> Mais aujourd'hui, comme j'avais du temps pour compléter la dernière page et tenter une mise en ligne, je me suis reconnectée via un marque page que je m'étais mis sur scribouilli et je ne retombe pas sur mon projet, mais sur le site : [https://scribouilli.github.io/scribouilli/atelier-list-pages?repoName=test-website-repo-3796&account=[object%20Object]](https://scribouilli.github.io/scribouilli/atelier-list-pages?repoName=test-website-repo-3796&account=%5Bobject%20Object%5D)
Est ce qu'il existe une possibilité pour que je retrouve mon projet en cours?

J'ai trouvé 🎉 C'est fixé avec https://github.com/Scribouilli/scribouilli/pull/40.

**Comment by Ynote** [comment]
@maiwann Sur les bugs listés dans cette issue, il reste ça pour l'instant 

> Note bis : J'ai reçu un mail de Github qui a l'air de dire que qqchose va pas alors que ma modif (de style) a fonctionné ?

Je m'en occupe en fin de semaine si c'est ok pour toi. Ou si d'autres personnes sont motivées :D

**Comment by Ynote** [comment]
> Du coup est-ce que ça affiche une fausse erreur ?
> Est-ce qu'on veut décourager les gens de mettre des espaces ?
> Est-ce qu'il faut qu'on gère les espaces d'une façon différente ?

Say bon \o/ Avec #42, on peut créer sans erreur des sites avec des espaces et des caractères spéciaux. Je clean tout côté back avant d'envoyer le call à l'API Github.

**Comment by Ynote** [comment]
> Note bis : J'ai reçu un mail de Github qui a l'air de dire que qqchose va pas alors que ma modif (de style) a fonctionné ?

@maiwann Après petit enquête 🔍, c'est normal de recevoir ce mails transactionnel si tu fais plusieurs modifs d'affilée sur différentes pages ou styles. GitHub Actions annule automatiquement les déploiements s'il y en a un nouveau en cours. 

Pour gérer les emails transactionnels de GitHub, il y a [cette documentation](https://docs.github.com/fr/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-email-preferences/types-of-emails-github-sends#notification-emails) qu'on pourrait ajouter dans notre documentation également. Je n'ai pas trouvé de moyen pour gérer ça directement via l'API GitHub.

**Comment by maiwann** [comment]
Merci @ynote pour tous ces fix <3
