### ISSUE TITLE
🔩 Configurer les options du dépôt Git créé via Scribouilli

### ISSUE THREAD

**Issue by Ynote** [daktary-team/scribouilli#34]
cf. https://github.com/Scribouilli/scribouilli/pull/33#discussion_r1236784181

Avec la génération d'un site Scribouilli à partir d'un [dépôt template](https://github.com/Scribouilli/site-template) au lieu d'une création de dépôt basique, on perd certaines options qu'on avait auparavant avec le call API à `POST api.github.com/user/repos` : 
```js
{
  name: repoName,
  homepage: publishedWebsiteURL,
  has_issues: false,
  has_projects: false,
  has_wiki: false,
  auto_init: false,
```

Cette issue sert pour discuter si ces options sont importantes ou non et si on doit faire un call pour les mettre en place.

**Comment by elegaanz** [comment]
Pour moi `homepage` est un peu important, le reste pas tant que ça, mais quitte à faire un appel à l'API autant tout mettre.
