### ISSUE TITLE
🐞 [Bloquant] Bug mystérieux avec isomorphic git

### ISSUE THREAD

**Issue by Ynote** [daktary-team/scribouilli#49]
## Description

Je pose ici quelques retours de différentes personnes.

Mail reçu : 
> Hello la Team Scribouilli !
> J'ai un bug reproduit sur deux de mes sites Scribouilli comme dit dans  l'objet :
> Les Pages de mes sites Scribouilli ne sont plus listées dans l'atelier (cf capture d'écran en pièce jointe)
> Est-ce que vous avez déjà eu des retours similaires ? Du coup je dois passer par GitHub pour mettre à jour les sites, ce qui enlève son charme à l'outil :nerd_face:
> Merci pour votre temps, bonne journée !
> Mathieu

Screenshot : 
![image](https://github.com/Scribouilli/scribouilli/assets/548778/60bdd863-5b46-48ef-b810-9b777a4c5d4c)

Erreur en console (sur un de mes sites en prod : 
<img width="960" alt="erreur en prod" src="https://github.com/Scribouilli/scribouilli/assets/548778/ade5b8b7-fc0a-48ed-8114-011de8949aaf">

## Premier diagnostic

Le clonage du dépôt Git a l'air de poser souci. Je pose ici la stack trace avec quelques `console.log` : 
<img width="960" alt="erreur dev 01" src="https://github.com/Scribouilli/scribouilli/assets/548778/ec552c6a-c31a-4f4d-8988-33752ad77162">
<img width="960" alt="erreur dev 02" src="https://github.com/Scribouilli/scribouilli/assets/548778/903a4381-ed52-408e-ac43-ba4c1fe2f762">

**Comment by DavidBruant** [comment]
Ce problème avait lieu après le passage à isomorphic-git
Ce passage a été revert temporairement

**Comment by DavidBruant** [comment]
Je peux reproduire le `ENOTDIR`
Dans la stack trace, on peut voir que y'a un problème dans `getPagesList`
~~Quand je log, je vois à un moment que l'argument `dir` est `<empty string>`~~
~~Je vais continuer l'enquête en suivant ce fil~~

~~Par ici, y'a un appel à `getPagesList` sans 3ème argument~~

~~https://github.com/Scribouilli/scribouilli/blob/ed00af1799600812631a1f623144ce3e08c5c73c/assets/scripts/actions.js#L103~~

Fausse piste rayée

**Comment by DavidBruant** [comment]
Par ici, y'a un appel à `getPagesList` sans 3ème argument

https://github.com/Scribouilli/scribouilli/blob/ed00af1799600812631a1f623144ce3e08c5c73c/assets/scripts/actions.js#L103

**Comment by elegaanz** [comment]
Normalement c'est ok de faire ça, ça permet de lister les fichiers à la racine du dépôt. Le paramètre `dir` est là si on veut explicitement lister un autre dossier (genre `_posts/`)

**Comment by DavidBruant** [comment]
Je crois que j'ai un problème autour du clone aussi
Quand je log dans `cloneIfNeeded`, j'ai plusieurs fois `dirExists false` alors que je m'attendrais à ce qu'à un moment, il retourne `true` parce qu'il a réussi à cloner une fois

**Comment by DavidBruant** [comment]
J'ai supprimé IndexedDB pour repartir de zéro
et là le clone fonctionne, même après un hard refresh :thinking: 

C'est très mystérieux

**Comment by DavidBruant** [comment]
En clonant un autre repo, j'ai pu tombé sur la même erreur que Fanny avec le split

```
Uncaught (in promise) TypeError: can't access property "split", text is null
    GitConfig index.js:1604
   (...)
    setAuthor databaseAPI.js:143
    setSiteRepoConfig actions.js:199
    promise callback*setSiteRepoConfig actions.js:199
    setCurrentRepositoryFromQuerystring actions.js:177
    atelierListPages atelier-list-pages.js:22
```

Mais je me demande si ce n'est pas parce qu'il y a un fichier qui n'a pas été créé avec scribouilli et donc ne respecte pas certaines conventions

**Comment by DavidBruant** [comment]
Sur l'histoire du clone et du dossier lightning-fs qui n'existe pas, j'avoue que je suis un peu perdu

Je n'arrive plus à reproduire le problème, donc ça devient impossible d'enquêter +

**Comment by elegaanz** [comment]
Je vais regarder de mon côté pour voir si j'arrive à reproduire.

**Comment by elegaanz** [comment]
Infos supplémentaires (copiées depuis le framateam) : 

- on a réussi à reproduire en créant un nouvel article, au moment de faire le `git add` du nouveau fichier, le chemin du fichier est vide et isomorphic-git plante en disant `path must not be empty`. Après ce premier plantage, on a systématiquement un `ENOTDIR` quand on revient sur la liste des pages.
- ce qui cause ce ENOTDIR visiblement c'est que les métadonnées de l'entrée correspondant à la racine du dépôt indiquent que le type est `'file'` (alors que ça devrait être `'dir'`), donc c'est pas tant que le dossier existe pas le souci, mais plutôt qu'il est « corrompu » et que lightning-fs nous dit que c'est un fichier alors que non (il y a bien des fichiers/dossiers enfants)
On va continuer à investiguer un peu, on vous tiendra au courant

On va faire continuer à faire des expérimentations sur la branche [`git-le-retour`](https://github.com/Scribouilli/scribouilli/tree/git-le-retour), si jamais vous voulez tester vous pouvez le faire sur https://davidbruant.github.io/scribouilli/ mais il faut bien penser à vider le cache et à supprimer tout ce qu'il y a dans IndexedDB avant.

**Comment by elegaanz** [comment]
Update des investigations : les deux points que j'explique au-dessus sont en fait totalement reliés. isomorphic-git râle parce qu'on fait un `git add ""` mais si ce chemin est vide ça veut dire que juste avant on écrit dans le fichier `this.path(login, repo, "") = "/github.com/LOGIN/REPO"` qui est un dossier et pas un fichier. Mais au lieu de râler, lightning-fs ne dit rien et transforme gentiment le dossier en un fichier du même nom. Et du coup on a plus de dossier, et du coup `ENOTDIR` !

**Comment by elegaanz** [comment]
A priori c'est réglé ! :))
