### ISSUE TITLE
Ajout du serveur Git dédié aux mini-sites Framalibre

### ISSUE THREAD

**Issue by Ynote** [daktary-team/scribouilli#53]
Lié à https://framagit.org/DavidBruant/brouillon-framalibre/-/issues/124

Pour Framalibre, on va avoir besoin de pouvoir pusher sur une instance GitLab dédiée. L'instance s'appellerait ScribouGit et on imagine s'en servir ensuite pour les sites scribouillis.

**Comment by DavidBruant** [comment]
On a créé https://git.scribouilli.org/
