### ISSUE TITLE
:ant: Je peux choisir l'ordre des pages 👍 👍 👍

### ISSUE THREAD

**Issue by elegaanz** [daktary-team/scribouilli#81]
- [x] Ajouter un champ `order` dans le front-matter
- [x] Le prendre en compte dans mimoza, par exemple [comme ça](https://gitlab.com/maiwann/folio/-/blob/master/_includes/header.html#L23) (penser au cas où le champ n'est pas défini dans le front-matter, je crois que cet exemple ne le gère pas)
- [x] Ajouter un bouton « Changer l'ordre » en bas de la liste des pages/articles
- [x] Quand on clique dessus, le bouton « Modifier » devient un champ nombre avec l'indice / order de la page, et le bouton devient un bouton « Enregistrer l'ordre »

**Comment by elegaanz** [comment]
Une super maquette

![image](https://github.com/Scribouilli/scribouilli/assets/16254623/1cc88425-b758-436c-8136-53894476fec6)

**Comment by maiwann** [comment]
Comportement étrange @clarabistouille : Chez https://github.com/bnjbvr/ma-semaine-chez-maiwann/commit/0bdd7394622ce87f383877e93075a7588431d611 il n'y a pas d'order à la création du dépôt, mais lorsque la page Accueil est modifiée, il y a un ```order : 3``` qui se rajoute.

Est-ce que c'est un bug ?

**Comment by clarabistouille** [comment]
Non c'est pas un bug ! 
En gros pour que le `order` arrive petit à petit sur les pages, j'ai fait un sorte que lorsqu'on enregistre, il soit calculé (actuellement, c'est l'ordre de base qui est pris en compte, donc alphabétique). Après je peux aussi me débrouiller pour qu'il reste à 0 tant qu'on ne le modifie pas si c'est plus intuitif ?

**Comment by maiwann** [comment]
Aha merci du détail ! A la réflexion je préfèrerai que :
1. Accueil soit en premier par défaut (si c'est pas trop chiant) à la création du site
2. On ne touche à rien sauf si l'utilisateurice change l'ordre (pour pas que les pages changent d'ordre sans action volontaire de la part de l'utilisateur)

Est-ce que ça génère des effets auxquels je ne pense pas, ce que je propose ?

**Comment by clarabistouille** [comment]
J'ai pas l'impression qu'il y ait des effets secondaires vu comme ça, en plus Accueil ne devrait pas être trop compliqué à mettre en premier parce que c'est par défaut index.md

Je préviens s'il y a des problèmes qui se soulèvent

**Comment by maiwann** [comment]
Merciii 🙏

**Comment by clarabistouille** [comment]
Du coup après réflexion, pour un site nouvellement créé, il faut juste que je touche 3 lignes au template donc ça va. Par contre pour les sites qui sont déjà créé, est-ce qu'on essaye aussi de mettre accueil en premier ? Sachant que si on veut faire ça, il va falloir quand même ajouter des `order` à toutes les pages parce que si on en met pas, dans le menu ça mets dans l'ordre : 
- toutes les pages sans order par ordre alphabétique
- un espace bizarre (le `li` vide je crois)
- les pages avec un order (donc ici seulement l'Accueil)

Ce qui nous met l'Accueil en tout dernier au final 😓

**Comment by maiwann** [comment]
Non on fait que pour les nouveaux c'est ok =)

**Comment by clarabistouille** [comment]
J'ai une petite question : dans la logique du "tant que l'utilisateur ne change pas l'ordre, aucun `order` n'est changé/ajouté automatiquement", j'ai modifié la valeur de cet `order` dans les nouvelles pages (avant on prenait le nombre de pages sur le site pour mettre la nouvelle page à la fin, maintenant il n'y a aucun `order`).

Ça marche bien pour les anciens sites où aucune page n'a de base d'ordre sauf si on l'ajoute. Mais dans les nouveaux sites où on souhaite l'Accueil en première page, toutes les pages ont des `orders` et ça met donc la nouvelle page un peu à part, et surtout avant les autres pages.

Ma question c'est donc : 
- est-ce qu'on privilégie les anciens sites en ne mettant pas d'`order` dans les nouvelles pages mais ça force les nouveaux sites à le faire (sinon la nouvelle page est en première page)
- on bien on fait l'inverse et les anciens sites doivent enlever l'`order` des nouvelles pages mais pour les nouveaux sites y'a rien à faire ?

**Comment by maiwann** [comment]
Après appel avec @clarabistouille on va mettre un ```order``` sur toutes les pages 

Ca va chambouler l'ordre des pages des anciens sites (qui n'ont pas d' ```order``` ) mais ça sera résolu dès que les personnes auront rajouté un ```order``` à leurs pages

**Comment by clarabistouille** [comment]
La branche est déployée sur https://elegaanz.github.io/scribouilli/ pour tester ! (Avec tous les derniers changements)

**Comment by maiwann** [comment]
Je viens de modifier l'ordre des pages de scribouilli.org et fandragrace et tout s'est bien passé :)

Ca serait cool si une personne technique pouvait jeter un oeil 👀 @DavidBruant @Ynote @yaf ?

**Comment by DavidBruant** [comment]
Chuis un peu perdu
Elle est finie cette issue ou pas ?
Est-ce qu'il y a encore besoin de jeter un coup d'œil technique ? (et si oui, où ? Est-ce qu'il y a une PR ?)

**Comment by DavidBruant** [comment]
Je pense que ça a été fini ici : https://github.com/Scribouilli/scribouilli/pull/97
