### ISSUE TITLE
Dans un dépôt partagé, gérer le cas où deux personnes éditent le site en simultané

### ISSUE THREAD

**Issue by elegaanz** [daktary-team/scribouilli#88]
- si c'est pas la même page, on peut catch l'exception, pull, faire un merge commit, et re-push
- si c'est la même page, on va sans doute avoir des conflits, et là c'est mieux d'avertir la personne que quelqu'un vient de modifier cette page et qu'il faut rafraîchir pour voir la nouvelle version

**Comment by DavidBruant** [comment]
La situation se présente aussi quand une personne joue avec l'atelier Scribouilli et github pendant la même session

On a eu une discussion aujourd'hui avec @Ynote et on a rajouté une nuance :
Quand y'a un conflit (le merge/rebase/cherry-pick échoue), on peut créer des tags sur les 2 branches divergentes et pousser ces tags (comme ça, aucun contenu n'est perdu).

Puis, proposer à la personne 3 options : 
1) attendre avant de prendre une décision et papoter avec les autres personnes pour clarifier quelle serait la meilleure résolution
2) imposer la version de la personne (et perdre la version "commune" (en mettant un lien vers le tag sur github/gitlab en mode "bonne chance !"))
3) imposer la version "commune" (et la personne perd sa version locale (en mettant un lien vers le tag sur github/gitlab en mode "bonne chance !"))

**Comment by DavidBruant** [comment]
isomorphic-git n'implémente ni rebase, ni cherry-pick, ni patch
https://github.com/isomorphic-git/isomorphic-git/issues/1736#issuecomment-1478153629
Ça va compliquer nos affaires... hmm...

**Comment by DavidBruant** [comment]
Mais on a le merge, donc on peut utiliser ça

Un pull, c'est jamais qu'un [fetch + merge + checkout](https://github.com/isomorphic-git/isomorphic-git/blob/4e09a739ec8df6b513535df168b624df9baeb88d/src/commands/pull.js#L84-L120), donc on peut faire :
- un fetch
- un test de merge (avec l'option `dryRun`)
- si ça marche, on merge (avec fastForward quand c'est possible)
- si le merge ne marche pas, on rajoute un conflit dans le store et on propose les 2 choix (imposer la version locale à distance ou imposer localement la version distante). Quand on impose la version locale, c'est un force-push. Quand on impose la version distante, c'est un déplacement de la branche principale pour qu'elle colle avec la version de la remote (branch avec l'argument `force`, je crois ?)
