### ISSUE TITLE
file-moi-les-clefs va perdre son hébergement

### ISSUE THREAD

**Issue by DavidBruant** [daktary-team/scribouilli#9]
Heroku arrête son plan gratuit, donc file-moi-les-clefs va perdre son hébergement (22 novembre si je comprends bien) 

Ptèt le prochain truc à taffer

Ptèt loccasion de rafraichir un peu le code aussi pour le mettre dans un style plus moderne/long terme (support natif ESM de Node.js)
https://github.com/daktary-team/file-moi-les-clefs

**Comment by DavidBruant** [comment]
https://file-moi-les-clefs.herokuapp.com/ n'est plus

Ptèt héberger sur [CleverCloud](https://www.clever-cloud.com/fr/tarification/) (4,5€/mois)

**Comment by Booteille** [comment]
C'est hébergé sur mon serveur perso' pour le moment.
