### ISSUE TITLE
Scribouilli enlève les issues, projects et wiki des repos existants quand on modifie une page

### ISSUE THREAD

**Issue by DavidBruant** [daktary-team/scribouilli#93]
Suite à https://github.com/Scribouilli/scribouilli/pull/92

Chuis un peu gêné de ce comportement. Des fois, j'ai des repo avec des issues, je veux bien modifier les markdown avec Scribouilli, mais pas enlever mes issues pour autant
Il est possible de remettre les issues en allant dans les settings du repo, 
mais le faire après chaque utilisation de Scribouilli, c'est relou
(je ne sais pas le détail pour les wiki et repo)

Côté solution, est-ce que ça serait ok qu'on laisse les repo existants tranquilles et qu'on ne configure que les repo que les gens créent directement via Scribouilli ? (j'ai envie d'appliquer ça aussi pour le topic site-scribouilli ; ptèt on peut le rajouter sur les repo existants qui s'appellent test-website-niania parce qu'on sait que ceux-là sont sûrement de notre faute :-p )

**Comment by Ynote** [comment]
C'est ok en production, je viens de tester 🎉 Il faut bien faire un `Ctrl`+`Maj`+`r` pour mettre à jour l'atelier pour bien avoir la dernière version du code pour que ça marche.
