### ISSUE TITLE
[Bug] Si je modifie un titre en y rajoutant un "?", la page ou l'article disparait

### ISSUE THREAD

**Issue by maiwann** [daktary-team/scribouilli#99]
Les détails sont là : [bug_article_scribouilli_?.pdf](https://github.com/Scribouilli/scribouilli/files/12419883/bug_article_scribouilli_.pdf)

Le problème se produit sur les articles comme sur les pages.

**Comment by elegaanz** [comment]
Pour le suppression / recréation immédiate il me semble que c'est parce que l'algo pour renommer un fichier marche comme ça.

J'ai l'impression que le souci c'est qu'on push quand on a supprimé, mais avant d'avoir re-créé le fichier avec le nouveau nom. Et donc quand on fait un autre changement, le commit de re-création est aussi push, et l'article ré-apparaît.

**Comment by yaf** [comment]
J'ai essayé en changement simplement les mots, et l'article disparait aussi. Ça renforce ce que tu dis @elegaanz, ça ne vient pas vraiment du caractère spécial, mais plutôt de l'enchainement d'opération Git lié au changement de titre
